spring.datasource.url=jdbc:postgresql://dpg-d8eect6rnols73a75d70-a.oregon-postgres.render.com:5432/e4db
spring.datasource.username=e4db_user
spring.datasource.password=F2psWeCU6dtGzmrtmf6OdnlWKMmm5SLz
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect