spring.datasource.url=${postgresql://pc02_nkg4_user:PggDAFNSTE4PmbJAjMNqOlsm7ZuMwvFs@dpg-d8c8vssp3tds73b44j4g-a/pc02_nkg4}
spring.datasource.username=${pc02_nkg4_user}
spring.datasource.password=${PggDAFNSTE4PmbJAjMNqOlsm7ZuMwvFs}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect